import { Open_Sans, Poppins } from "next/font/google";
import localFont from "next/font/local";
import Providers from "@/app/providers";
import "@/public/css/fontello.css";
import "@/app/globals.css";
import AuthDialog from "@/components/authentication/AuthDialog";
import Script from "next/script";
import AcceptYourOffer from "@/components/getoffers/pages/AcceptYourOffer";
import { Toaster } from "react-hot-toast";
import Notifications from "@/components/dashboard/notification/Notifications";
import process from "next/dist/build/webpack/loaders/resolve-url-loader/lib/postcss";
import { GoogleTagManager } from "@next/third-parties/google";
import { FacebookPixelEvents } from "@/components/FacebookPixelEvents";
import { Suspense } from "react";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--open-sans",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--poppins",
});
const helvetica = localFont({
  variable: "--helvetica",
  src: [
    {
      path: "../public/assets/fonts/helvetica.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/helvetica-light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/helvetica-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Happy Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <GoogleTagManager gtmId={"GTM-PMHRHNJD"} />
      <head>
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY}&libraries=places`}
          strategy="beforeInteractive"
        />

        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=AW-11503511349"
        />
        <Script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'AW-11503511349');
            `,
          }}
        />

        <Script
          dangerouslySetInnerHTML={{
            __html: `
              gtag('event', 'conversion', {
                  'send_to': 'AW-11503511349/c3prCLno7vgZELXOpu0q',
                  'value': 1.0,
                  'currency': 'USD'
              });
            `,
          }}
        />

        <Script
          dangerouslySetInnerHTML={{
            __html: `
              gtag('event', 'conversion', {
                  'send_to': 'AW-11503511349/iK7zCNvQ2_8ZELXOpu0q',
                  'value': 1.0,
                  'currency': 'USD'
              });
            `,
          }}
        />

        <title>Happy Home</title>
      </head>
      <body
        className={`${openSans.variable} ${poppins.variable} ${helvetica.variable} h-full`}
      >
        <Providers>
          <AuthDialog />
          <AcceptYourOffer />
          <Toaster position="top-center" />
          <Notifications />
          {children}
        </Providers>

        <Suspense fallback={null}>
          <FacebookPixelEvents />
        </Suspense>
      </body>
    </html>
  );
}
