import Header from "@/components/header/header";

export const metadata = {
  title: "Happy Home",
  description: "Generated by create next app",
};

export default async function HomePageLayout({ children }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
