import DashboardAside from "@/components/dashboard/DashboardAside";
import DashboardHeader from "@/components/dashboard/DashboardHeader";

export const metadata = {
  title: "Happy Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <div
      className={
        "grid grid-cols-1 xl:grid-cols-[247px_1fr] h-[100vh] bg-gray-3 overflow-y-auto"
      }
    >
      <DashboardAside />
      <div className={"flex flex-col overflow-y-auto h-full"}>
        <DashboardHeader />
        <div className={"relative h-[calc(100%_-_81px)]"}>{children}</div>
      </div>
    </div>
  );
}
